### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by fabra** [L-Acoustics/avdecc#102]
Many projects are doing this to address cultural change. The side effect is that  working with git submodules in a Jenkins environment becomes a nightmare. Therefore it would be helpful to unify the name of this branch and the associated submodules.

see https://github.com/github/renaming

**Comment by christophe-calmejane** [comment]
Thanks for the reminder, it's something in my list, but many scripts all over the place are expecting "master", so it will be a long process before we can change branch name.

**Comment by christophe-calmejane** [comment]
Actually, most of my scripts were already updated, I updated the remaining ones.
