### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by andrew-elder** [L-Acoustics/avdecc#118]
I'm seeing compile errors...

```
$ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
/avdecc/examples/src/utils.cpp: In function ‘void outputText(const string&)’:
/avdecc/examples/src/utils.cpp:95:24: error: format not a string literal and no format arguments [-Werror=format-security]
   95 |                 wprintw(s_Window, str.c_str());

```

using branch **dev**

```
$ git log --oneline
4b43887 (HEAD -> dev, origin/dev) Fixed rare crash during entity enumeration
```
I can add -Werror=format-security to the cmake file is that is the recommended fix.

**Comment by christophe-calmejane** [comment]
Thanks I'll take a look tomorrow.
Unfortunately I didn't add the dockerfiles to this repo, easier to get a stable dev env 😜
Will fix this as well!

**Comment by christophe-calmejane** [comment]
Hum that's weird, I don't have any issue when building from the docker env, same compiler version (`gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0`), no warning whatsoever.
I guess the simplest solution would be to fix the actual error, can you try on your system to insert `"%s"` as second parameter to the `wprintw` call?

**Comment by andrew-elder** [comment]
@christophe-calmejane - that suggestion worked, thanks. Do you want me to make a branch and merge request, or do you just want to make the change?

**Comment by christophe-calmejane** [comment]
Please do, it's always good to have many contributors to a projet ;)

**Comment by andrew-elder** [comment]
PR created.

**Comment by christophe-calmejane** [comment]
Thanks
