### ISSUE TITLE
API for associating application-specific data with handles

### ISSUE THREAD

**Issue by lhoward** [L-Acoustics/avdecc#137]
It would be useful for all the handle-related APIs in the C bindings to allow the associated of application-specific data that can then be retrieved in the callbacks.

e.g.

```c
LA_AVDECC_BINDINGS_C_API avdecc_local_entity_error_t LA_AVDECC_BINDINGS_C_CALL_CONVENTION 
LA_AVDECC_LocalEntity_setApplicationData(LA_AVDECC_LOCAL_ENTITY_HANDLE const handle, void *data);
LA_AVDECC_BINDINGS_C_API avdecc_local_entity_error_t LA_AVDECC_BINDINGS_C_CALL_CONVENTION 
LA_AVDECC_LocalEntity_getApplicationData(LA_AVDECC_LOCAL_ENTITY_HANDLE const handle, void **data);
```

(Actually I'd prefer `LA_AVDECC_LocalEntity_getApplicationData()` to just return a `void *` as it makes casting easier but, perhaps you want to return an error in case of invalid handle etc.)

**Comment by lhoward** [comment]
I have an implemented which I'll file a PR for shortly.

**Comment by christophe-calmejane** [comment]
Thank you, I'll take a deeper look shortly, have important 1722.1-2021 stuff to add first.

**Comment by christophe-calmejane** [comment]
Merged. Thanks.
