### ISSUE TITLE
Linux: doesn't compile with g++ 13

### ISSUE THREAD

**Issue by benoit-quiniou** [L-Acoustics/avdecc#149]
This is due to new default warning flags in g++ release.Can be fixed with adding:

```cmake
set(CMAKE_CXX_FLAGS "-Wno-c++20-compat")
```

to the CMakeLists.txt.

**Comment by christophe-calmejane** [comment]
I introduced a new mechanism to set compilation flags based on the compiler: Please take a look at the local_definition.cmake file in the root directory. Don't hesitate to provide a pull request if it is working fine for you. Thanks

**Comment by benoit-quiniou** [comment]
Sorry for the delay. I find no trace of a local_definition.cmake file in root directory, nor reference to it in existing files, nor commit changes containing ```local_definition.cmake```. Do I miss something ?

**Comment by christophe-calmejane** [comment]
Hi, I forgot to mention that you should be using the 'dev' branch for any issues (I should actually configure the repository to defaults to that branch). It will be released quite soon anyway.
The file is named local_definitions.cmake (with an 's') in the root folder.

**Comment by benoit-quiniou** [comment]
Sorry, I overlooked the dev branch when searching.
In that branch the issue doesn't happen anymore anyway, thanks to some ```fmtlib``` update, where some traits classes are now doing good job to detect the existence of c++20 types.
BTW, Error output used to be:
```sh
[ 18%] Building CXX object src/CMakeFiles/la_avdecc_cxx.dir/endStationImpl.cpp.o
In file included from /home/benoit/dev/Hive/3rdparty/avdecc/externals/3rdparty/fmtlib/include/fmt/format.h:36,
                 from /home/benoit/dev/Hive/3rdparty/avdecc/src/logHelper.hpp:39,
                 from /home/benoit/dev/Hive/3rdparty/avdecc/src/entity/entityImpl.hpp:34,
                 from /home/benoit/dev/Hive/3rdparty/avdecc/src/entity/controllerEntityImpl.hpp:33,
                 from /home/benoit/dev/Hive/3rdparty/avdecc/src/endStationImpl.cpp:26:
/home/benoit/dev/Hive/3rdparty/avdecc/externals/3rdparty/fmtlib/include/fmt/core.h:369:6: error: identifier ‘char8_t’ is a keyword in C++20 [-Werror=c++20-compat]
  369 | enum char8_t : unsigned char {};
      |      ^~~~~~~
```

Looking at it, I guess the ```local_definitions.cmake``` would make the job for adding the compiler flag.
Thank you for your time,  as far as we are concerned, this issue can be closed.
