### ISSUE TITLE
AVB controller for multiple interfaces

### ISSUE THREAD

**Issue by i-n-g-o** [L-Acoustics/avdecc#152]
On a system with multiple (AVB) interfaces only one controller can be created for the first interface found.

Trying to create more then one controller for the other interfaces results in this error-message:

`Could not create AVB controller on interface '...': ExecutorManager: Executor with name 'avdecc::protocol::PI' already exists.`

Happens with version 3.4.1 from the master-branch.

**Comment by christophe-calmejane** [comment]
Yes, you need to use the dev branch.

**Comment by i-n-g-o** [comment]
Ah, I see. Thanks for your answer.
