### ISSUE TITLE
build failed - field '_layer' const-qualified type

### ISSUE THREAD

**Issue by AWHubGit** [L-Acoustics/avdecc#65]
Bonjour. Je ne suis pas expert/programmer. J'essaye à compiler LA-avdecc sur macOS Mojave avec xcode. Ca me jete des erreurs. Il parait qu'une constante pour le logging a une mauvaise declaration. Je ne sais pas si c'est ma faute. Quoi faire?
Je voulais essayer LA_avdecc car ca utilise Apple’s native API control of the input and output AVB streams of a Mac.
Ci-joint screenshot erreurs xcode build
Salutations
AW
<img width="2048" alt="erreurs_build_LA_avdecc_2019-10-13 um 11 06 53" src="https://user-images.githubusercontent.com/10176767/66713406-e1cc5a00-edaa-11e9-8a42-d3001061e58e.png">

**Comment by christophe-calmejane** [comment]
Xcode 11 compilation errors are already fixed, but for that you need to use the latest 'dev' branch
