### ISSUE TITLE
crash with MacOSNative in weird state

### ISSUE THREAD

**Issue by i-n-g-o** [L-Acoustics/avdecc#73]
Hi.

We are experiencing crashes with a mac which is in a weird AVB state.

The "AVDECC Entity Controller" can find entities on the network, but can not resolve IDs. 
See this screenshot:

![macos-avb-weird-controller](https://user-images.githubusercontent.com/4501039/75479971-b4bac580-59a0-11ea-82f3-99c0491e31ad.png)

This state is somewhat persistent but seems not to be hardware-related: AVB operates normally on the same machine with a different OS.

The crash happens with `MacOSNative` on MacOS 10.14.6

The relevant parts from the crash report:

```
Crashed Thread:        6  Dispatch queue: com.apple.AudioVideoBridging.AVB17221EntityDiscovery.en0.callbackAction

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
abort() called
```

```
Thread 6 Crashed:: Dispatch queue: com.apple.AudioVideoBridging.AVB17221EntityDiscovery.en0.callbackAction
0   libsystem_kernel.dylib        	0x00007fff5c0692c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5c124bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5bfd36a6 abort + 127
3   libc++abi.dylib               	0x00007fff591b8641 abort_message + 231
4   libc++abi.dylib               	0x00007fff591b87c7 default_terminate_handler() + 243
5   libobjc.A.dylib               	0x00007fff5a76b783 _objc_terminate() + 105
6   libc++abi.dylib               	0x00007fff591c419e std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff591c4213 std::terminate() + 51
8   libdispatch.dylib             	0x00007fff5bee1651 _dispatch_client_callout + 28
9   libdispatch.dylib             	0x00007fff5bee78e0 _dispatch_lane_serial_drain + 602
10  libdispatch.dylib             	0x00007fff5bee8396 _dispatch_lane_invoke + 385
11  libdispatch.dylib             	0x00007fff5bef06ed _dispatch_workloop_worker_thread + 598
12  libsystem_pthread.dylib       	0x00007fff5c121611 _pthread_wqthread + 421
13  libsystem_pthread.dylib       	0x00007fff5c1213fd start_wqthread + 13
```

I tracked the crash down to `[BridgeInterface deinit]` in `protocolInterface_macNative.mm` - it gets called twice:
On time from `ProtocolInterfaceMacNativeImpl::shutdown()` and another time from its own `[BridgeInterface dealloc]`.

Avoiding this double `deinit` seems to fix the crash but i am not 100% sure what's happening.

This issue seems to be hard to reproduce so the mac keeps running in its weird state so we can run tests on it as long as it's needed.

Any thoughts on this?

**Comment by romansavrulin** [comment]
@i-n-g-o Can you describe your network setup more precisely? How and where do you run examples? What brings 0x000 entities to MACs avdecc controller?

**Comment by i-n-g-o** [comment]
I don't know the network topology, so i can't give more details right now.

Each 0x000 entity is a AVB device in the network. Looking at the network with a functioning controller shows the same amount of entities (and their respective ids of course)

Other controllers in the network work normally, so i doubt the problem is related to the specific network setup.

Running Hive on the same machine crashes as well.

**Comment by christophe-calmejane** [comment]
Although I do agree that the library should not crash in any case, if the underlying API is exposing undefined behavior it might be hard to conclude anything.
I will have to take another look at the macOS native implementation sometime in the near future, but I wouldn't rely on it (ie. use pcap if possible) as the API has a few bugs I reported to apple a while back. I yet have to check if all are fixed in the latest macOS version.

Thanks for the call stack it's very helpful!

**Comment by i-n-g-o** [comment]
The experiment with avoiding double-deinit was not successful, it still crashes.

**Comment by christophe-calmejane** [comment]
I found some time to update macOS native, I might have fixed this issue. As I guess it's not that easy to have your mac in this state, I'll close it. I'll push the commit soon so you can try. If the issue arises again, re-open the ticket.

**Comment by christophe-calmejane** [comment]
Possible fix in e744cd55de540e93de737af86a52a4394892fe3a

**Comment by i-n-g-o** [comment]
thanks!
unfortunately we lost the weird test-machine so i can't verify the fix works.
i will report here if we can run into this state again.

**Comment by i-n-g-o** [comment]
my machine now got into that same weird avb-state.

i can confirm that the fix works using the version on master tagged 3.0.
creating a controller now throws:
"Cannot create controller: Selected protocol interface type not supported"
