### ISSUE TITLE
no controller with MacOSNative since version 3.0

### ISSUE THREAD

**Issue by i-n-g-o** [L-Acoustics/avdecc#76]
using a build from current master (version 3.0) or current dev does not create a controller with protocol `MacOSNative`.

instead an exception with `Cannot create controller: Selected protocol interface type not supported` is thrown.

i tried version 3.0 on 10.14.6 and 10.14.5
tested version 3.0.1-beta1 on 10.14.6

**Comment by christophe-calmejane** [comment]
Hi,
as explained in this commit 0e1a4520fb111f774ca2131410b4b6f590665470, macOSNative is now restricted to Catalina and later (>= 10.5.x).
There were just too many bugs in Apple AVBFramework before Catalina for it to be usable for Milan devices.

**Comment by i-n-g-o** [comment]
Oh, i missed that commit-message.
Thanks for the explanation.
